version: 2

sources:
  - name: jaffle_shop
    database: RAW
    schema: JAFFLE_SHOP
    tables:
      - name: customers
      - name: orders

  - name: stripe
    database: RAW
    schema: STRIPE
    tables:
      - name: payment